### ISSUE TITLE
Enable Https

### ISSUE THREAD

**Issue by farley13** [TransparentWorld/Issues#18]
We should use the https build into amazon - this should be nearly a one click operation as amazon will issue a cert for itself. We should do this only for tranparentworld.org

**Comment by akarasev** [comment]
Do I understand correctly? 
We should enable HTTPS for an app in a PROD and modify Elastic Load Balancer to use a port 443 instead of a 80.
So, http://tranparentworld.org will turn into https://tranparentworld.org

**Comment by farley13** [comment]
Yeah - exactly - http://www.transparentworld.org -> https://www.transparentworld.org

**Comment by farley13** [comment]
@akarasev - looks good in dev - let's wait until it's deployed to close
