### ISSUE TITLE
301 all domains to transparentworld.org

### ISSUE THREAD

**Issue by farley13** [TransparentWorld/Issues#19]
We should setup s3 301 redirects to transparentworld.org from all of our other domains currently in AWS. See http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html and http://www.delightedrobot.com/338/amazon-s3-301-redirects/ for more info on s3 redirects.

**Comment by akarasev** [comment]
Didn't get the point. What kind of requests should be redirected. Please, provide an example.

**Comment by farley13** [comment]
Ah - anything to transparent-world.com for instance should be 301-ed. so 
www.transparent-world.com/ should 301 to www.transparentworld.org - 
www.transparent-world.com/article/2-elephant_poaching_ should 301 to www.transparentworld.org/article/2-elephant_poaching_

Looking at S3 again today - I think it's too limited to implement this correctly - I think it will be easier/simpler to simply do the redirect in the play app itself. Currently all domains are pointed to the same ELB

**Comment by akarasev** [comment]
What is the "transparent-world.com"?

**Comment by farley13** [comment]
So I ended up getting domains other than transparentworld.org - transparent-world.com is one example - transparentworld.net and transparent-world.net I think I got as well. Largely to try to cover users using the wrong domain. If you look at Route 53 config in AWS you'll see them all - they are all mapped to the same elastic LB.

**Comment by farley13** [comment]
@akarasev  This looks good to go
