### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by farley13** [TransparentWorld/Issues#65]
We should backup the production DB to S3 daily - it should be pretty small - and likely old copies won't need to be removed anytime soon.

**Comment by akarasev** [comment]
I'm thinking about implementation. What about a shell script into a VM instance with PostgresSQL container running? Shell script creates SQL dump and uploads it to S3 bucket using AWS CLI. To run it daily I'll create a cron task into the same VM instance.

**Comment by farley13** [comment]
sounds good to me - we should have the test db restore from the backup once a day as well - will help making sure the backups are working correctly as well. Having both built into the db image makes sense to me.

**Comment by akarasev** [comment]
To be aware about backup/restore status, wouldn't be better to create Jenkins job?

**Comment by farley13** [comment]
I'd be ok with either - as long we are alerted when it fails - jenkins
would be easier to keep an eye on - as long as it doesn't break if we need
to kill/redeploy a DB copy.

**Comment by farley13** [comment]
This is now on Jenkins - closing out. Will open separate ticket for auto-redeploy of postgres/solr/prometheus
