### ISSUE TITLE
Move remaining services over to jenkins deploy

### ISSUE THREAD

**Issue by farley13** [TransparentWorld/Issues#9]
Currently Jenkins is only deploying the web app to an auto-scale group - we should look to do the same for redis, solr. We likely should start with a single instance deploy for both for now (autoscale -> just 1 instance) - similar to the dev setup. The only critical thing here is ensuring we have actual uptime for both when AWS EAST inevitably goes down. It should spin up a new instance of either automatically if the old one is killed.

**Comment by farley13** [comment]
One comment here - if possible we should run all of these on 1 VM with the load balancer pointing to it - this hopefully is the most cost effective way of dealing with this. We can deal with some down time when we release until we have more traffic.

**Comment by akarasev** [comment]
If I've got it correctly. There is no point to use auto-scale group for Redis and Solr.

In fact auto-scale group is clusterization technology. However, Redis use their own cluster (see `redis-trib.rb`). If we will want to scale Solr horizontally, we should use its own sharding (e.g. [ZooKeeper](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#can-i-run-zookeeper-and-solr-clusters-under-docker))

"...if possible we should run all of these on 1 VM..." Yes, it is possible to run all of the our containers: PostrgreSQL, Solr and all Redis nodes on 1 VM. To be more precise 1 VM for TEST and 1 VM for PROD. 

I've never tried t2.nano. Should I try it or t2.micro is fine?

**Comment by farley13** [comment]
Let's try nano and if it's totally broken move up to micro?

**Comment by farley13** [comment]
Creating a new issue for the auto-redeploy of updated configuration/auto-recreation if the current VM goes down (my understanding would be that we would lose the DB changes and we'd need to manually spin a new VM up).
